export const IMAGE_GALLERY_OPEN = "IMAGE_GALLERY_OPEN";
export const IS_UPLOADING = "IS_UPLOADING";
export const IMAGE_GALLERY_CLOSED = "IMAGE_GALLERY_CLOSED";
export const RESET_STATE = "RESET_STATE";
