image: node:6.11.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm install exp -g
          - exp login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          - exp doctor