export const PASSWORD_ACCEPTED = "PASSWORD_ACCEPTED";
export const PASSWORD_NOT_ACCEPTED = "PASSWORD_NOT_ACCEPTED";
export const PASSWORD_VALID = "PASSWORD_VALID";
export const PASSWORD_INVALID = "PASSWORD_INVALID";
