export const FORM_HAS_ERRORS = "FORM_HAS_ERRORS";
export const UPDATE_IMAGES = "UPDATE_IMAGES";
export const IMAGE_GALLERY_OPEN = "IMAGE_GALLERY_OPEN";
export const IMAGE_GALLERY_CLOSED = "IMAGE_GALLERY_CLOSED";
export const SUBMIT_FORM_RQ = "SUBMIT_FORM_RQ";
export const UPDATE_LOADING_MESSAGE = "UPDATE_LOADING_MESSAGE";
export const SUBMIT_FORM_RS = "SUBMIT_FORM_RS";
export const RESET_STATE = "RESET_STATE";
