export const FORM_HAS_ERRORS = "FORM_HAS_ERRORS";
export const UPDATE_IMAGES = "UPDATE_IMAGES";
export const IMAGE_GALLERY_OPEN = "IMAGE_GALLERY_OPEN";
export const IMAGE_GALLERY_CLOSED = "IMAGE_GALLERY_CLOSED";
