export const FORM_HAS_ERRORS = "FORM_HAS_ERRORS";
export const UPDATE_PHOTOS = "UPDATE_PHOTOS";
export const PHOTO_GALLERY_OPEN = "PHOTO_GALLERY_OPEN";
export const PHOTO_GALLERY_CLOSED = "PHOTO_GALLERY_CLOSED";
